<a href="https://colab.research.google.com/github/GameLooped/Trbajos/blob/main/Ejercicios1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#pip install numpy

EJERCICIO 1

In [ ]:
curso = np.array (["Matemáticas", "Física", "Química", "Historia", "Lengua"])
print(curso)

['Matemáticas' 'Física' 'Química' 'Historia' 'Lengua']


EJERCICIO 2

In [ ]:
Asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]

for Asignatura in Asignaturas:
  print("Yo estudio", Asignatura, "donde", Asignatura, "es cada una de las asignaturas de la lista.")

Yo estudio Matemáticas donde Matemáticas es cada una de las asignaturas de la lista.
Yo estudio Física donde Física es cada una de las asignaturas de la lista.
Yo estudio Química donde Química es cada una de las asignaturas de la lista.
Yo estudio Historia donde Historia es cada una de las asignaturas de la lista.
Yo estudio Lengua donde Lengua es cada una de las asignaturas de la lista.


EJERCICIO 3

In [ ]:
Asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = []

for Asignatura in Asignaturas:
  nota = input(f"¿Qué nota has sacado en {Asignatura}? ")
  notas.append(nota)

print("\n--- Resumen de notas ---")
for i in range(len(Asignaturas)):
  print(f"En {Asignaturas[i]} has sacado {notas[i]}")


¿Qué nota has sacado en Matemáticas? 12
¿Qué nota has sacado en Física? 10
¿Qué nota has sacado en Química? 15
¿Qué nota has sacado en Historia? 05
¿Qué nota has sacado en Lengua? 20

--- Resumen de notas ---
En Matemáticas has sacado 12
En Física has sacado 10
En Química has sacado 15
En Historia has sacado 05
En Lengua has sacado 20


EJERCICIO 4

In [ ]:
numeros_loteria = []

print("Por favor, ingresa los 5 números ganadores de la lotería primitiva:")

for i in range(5):
  while True:
    try:
      numero = int(input(f"Ingresa el número {i+1}: "))
      numeros_loteria.append(numero)
      break
    except ValueError:
      print("Entrada no válida. Por favor, ingresa un número entero.")


numeros_loteria.sort()

print("\nLos números ganadores de la lotería ordenados de menor a mayor son:")
print(numeros_loteria)

Por favor, ingresa los 5 números ganadores de la lotería primitiva:
Ingresa el número 1: 15
Ingresa el número 2: 21
Ingresa el número 3: 500
Ingresa el número 4: 14
Ingresa el número 5: 01

Los números ganadores de la lotería ordenados de menor a mayor son:
[1, 14, 15, 21, 500]


EJERCICIO 5

In [ ]:
n = list(range(1, 11))
n.reverse()

print(",".join(map(str, n)))

10,9,8,7,6,5,4,3,2,1


EJERCICIO 6

In [ ]:
asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lengua"]
notas = {}

print("Por favor, ingresa la nota obtenida en cada asignatura:")
for asignatura in asignaturas:
  while True:
    try:
      nota = float(input(f"Nota en {asignatura}: "))
      notas[asignatura] = nota
      break
    except ValueError:
      print("Entrada no válida. Por favor, ingresa un número para la nota.")

asignaturas_a_repetir = []
nota_minima_aprobado = 10.0

for asignatura, nota in notas.items():
  if nota < nota_minima_aprobado:
    asignaturas_a_repetir.append(asignatura)

if asignaturas_a_repetir:
  print("\n--- Asignaturas a repetir ---")
  for asignatura in asignaturas_a_repetir:
    print(asignatura)
else:
  print("¡Felicidades! Has aprobado todas las asignaturas.")

Por favor, ingresa la nota obtenida en cada asignatura:
Nota en Matemáticas: 15
Nota en Física: 02
Nota en Química: 02
Nota en Historia: 15
Nota en Lengua: 03

--- Asignaturas a repetir ---
Física
Química
Lengua


EJERCICIO 7

In [ ]:
import string
abecedario = list(string.ascii_lowercase)
abecedario_filtrado = [letra for i, letra in enumerate(abecedario) if (i + 1) % 3 != 0]
print(abecedario_filtrado)

['a', 'b', 'd', 'e', 'g', 'h', 'j', 'k', 'm', 'n', 'p', 'q', 's', 't', 'v', 'w', 'y', 'z']


EJERCICIO 8

In [ ]:
palabra = input("Ingresa una palabra para verificar si es un palíndromo: ")
palabra_procesada = palabra.replace(" ", "").lower()
palabra_invertida = "".join(reversed(palabra_procesada))

if palabra_procesada == palabra_invertida:
  print(f"La palabra '{palabra}' es un palíndromo.")
else:
  print(f"La palabra '{palabra}' no es un palíndromo.")

Ingresa una palabra para verificar si es un palíndromo: RecOnocer
La palabra 'RecOnocer' es un palíndromo.


EJERCICIO 9

In [ ]:
palabra = input("Ingresa una palabra para contar sus vocales: ")
palabra = palabra.lower()

conteo_vocales = {'a': 0, 'e': 0, 'i': 0, 'o': 0, 'u': 0}

for caracter in palabra:
  if caracter in conteo_vocales:
    conteo_vocales[caracter] += 1
print("\nResultado del conteo de vocales:")
for vocal, cantidad in conteo_vocales.items():
  print(f"'{vocal}': {cantidad}")

Ingresa una palabra para contar sus vocales: HermeneguildoRuperezzza

Resultado del conteo de vocales:
'a': 1
'e': 5
'i': 1
'o': 1
'u': 2


EJERCICIO 10

EJERCICIO 11

In [ ]:
vector1 = [1, 2, 3]
vector2 = [-1, 0, 2]
producto_escalar = sum(v1 * v2 for v1, v2 in zip(vector1, vector2))
print(f"El producto escalar de {vector1} y {vector2} es: {producto_escalar}")

El producto escalar de [1, 2, 3] y [-1, 0, 2] es: 5


EJERCICIO 12

In [ ]:
matriz1 = np.array([[1, 2],[3, 4]])
matriz2 = np.array([[5, 6],[7, 8]])
lista_de_matrices = [matriz1, matriz2]
producto_matrices = lista_de_matrices[0] @ lista_de_matrices[1]
print("Matriz 1:")
print(lista_de_matrices[0])
print("\nMatriz 2:")
print(lista_de_matrices[1])
print("\nEl producto de las matrices es:")
print(producto_matrices)

Matriz 1:
[[1 2]
 [3 4]]

Matriz 2:
[[5 6]
 [7 8]]

El producto de las matrices es:
[[19 22]
 [43 50]]


EJERCICIO 13

In [ ]:

muestra_str = input("Ingresa una muestra de números separados por comas: ")
numeros_str = muestra_str.split(',')

try:
  numeros = [float(num.strip()) for num in numeros_str]

  if not numeros:
    print("No se ingresaron números.")
  else:
    media = np.mean(numeros)
    desviacion_tipica = np.std(numeros)
    print(f"\nLa media de la muestra es: {media:.2f}")
    print(f"La desviación típica de la muestra es: {desviacion_tipica:.2f}")
except ValueError:
  print("Error: Asegúrate de ingresar números válidos separados por comas.")

Ingresa una muestra de números separados por comas: 45, 68, 87

La media de la muestra es: 66.67
La desviación típica de la muestra es: 17.17
